spring.application.name=tpbatch
 spring.profiles.active=postgresql

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none

logging.level.com.example.tpbatch = INFO
spring.batch.job.enabled=false

#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

urlCsv=https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/adresses-79.csv.gz
file=./data/adresses-79.csv
tempFile=./data/addrTemp.csv
outputDir=./data/tmp

numberOfThread=8
chunkSize=10000
