spring.application.name=tpbatch

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.schema-locations=classpath:schema.sql

spring.datasource.url=jdbc:sqlite:./src/main/resources/data/ban.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

logging.level.com.example.tpbatch = info
spring.batch.job.enabled=false

file=data/adresses-france.csv
