ALTER TABLE t_dvf RENAME TO t_dvf_old;

CREATE TABLE IF NOT EXISTS t_dvf(
    id_mutation TEXT PRIMARY KEY,
    date_mutation TEXT,
    numero_disposition TEXT,
    nature_mutation TEXT,
    valeur_fonciere NUMERIC,
    adresse_numero TEXT,
    adresse_suffixe TEXT,
    adresse_nom_voie TEXT,
    adresse_code_voie TEXT,
    code_postal TEXT,
    code_commune TEXT,
    nom_commune TEXT,
    code_departement TEXT,
    ancien_code_commune TEXT,
    ancien_nom_commune TEXT,
    id_parcelle TEXT,
    ancien_id_parcelle TEXT,
    numero_volume TEXT,
    lot1_numero TEXT,
    lot1_surface_carrez NUMERIC,
    lot2_numero TEXT,
    lot2_surface_carrez NUMERIC,
    lot3_numero TEXT,
    lot3_surface_carrez NUMERIC,
    lot4_numero TEXT,
    lot4_surface_carrez NUMERIC,
    lot5_numero TEXT,
    lot5_surface_carrez NUMERIC,
    nombre_lots INTEGER,
    code_type_local TEXT,
    type_local TEXT,
    surface_reelle_bati NUMERIC,
    nombre_pieces_principales INTEGER,
    code_nature_culture TEXT,
    nature_culture TEXT,
    code_nature_culture_speciale TEXT,
    nature_culture_speciale TEXT,
    surface_terrain NUMERIC,
    longitude NUMERIC,
    latitude NUMERIC,
    hash INTEGER
);