ALTER TABLE t_dvf RENAME TO t_dvf_old;

CREATE TABLE IF NOT EXISTS t_dvf(
    id_mutation VARCHAR PRIMARY KEY,
    date_mutation VARCHAR,
    numero_disposition VARCHAR,
    nature_mutation VARCHAR,
    valeur_fonciere NUMERIC,
    adresse_numero VARCHAR,
    adresse_suffixe VARCHAR,
    adresse_nom_voie VARCHAR,
    adresse_code_voie VARCHAR,
    code_postal VARCHAR,
    code_commune VARCHAR,
    nom_commune VARCHAR,
    code_departement VARCHAR,
    ancien_code_commune VARCHAR,
    ancien_nom_commune VARCHAR,
    id_parcelle VARCHAR,
    ancien_id_parcelle VARCHAR,
    numero_volume VARCHAR,
    lot1_numero VARCHAR,
    lot1_surface_carrez NUMERIC,
    lot2_numero VARCHAR,
    lot2_surface_carrez NUMERIC,
    lot3_numero VARCHAR,
    lot3_surface_carrez NUMERIC,
    lot4_numero VARCHAR,
    lot4_surface_carrez NUMERIC,
    lot5_numero VARCHAR,
    lot5_surface_carrez NUMERIC,
    nombre_lots INTEGER,
    code_type_local VARCHAR,
    type_local VARCHAR,
    surface_reelle_bati NUMERIC,
    nombre_pieces_principales INTEGER,
    code_nature_culture VARCHAR,
    nature_culture VARCHAR,
    code_nature_culture_speciale VARCHAR,
    nature_culture_speciale VARCHAR,
    surface_terrain NUMERIC,
    longitude NUMERIC,
    latitude NUMERIC,
    hash BIGINT
);